# This is a basic workflow to help you get started with Actions

name: Snack

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
        echo "This is a new file." > xxx2.txt
    - name: generate report
      uses: Platane/snk@v2
      with:
        # github user name to read the contribution graph from (**required**)
        # using action context var `github.repository_owner` or specified user
        github_user_name: ${{ github.repository_owner }}
        outputs: 
          ./assets/github-snake.svg
          ./assets/github-snake-dark.svg?palette=github-dark
          ./assets/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
    - name: Commit files
      run: |
        git config --global user.email xieyongbo@tom.com
        git config --global user.name ellioben
        git add .
        git commit -a -m "Update changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        branch: ${{ github.ref }}

