name: New File Workflow

on:
  push:
    branches:
      - master

jobs:
  create_new_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Git
        run: |
          git config --global user.email "xieyongbo@tom.com"
          git config --global user.name "Ellioben"

      - name: Create new file
        run: |
          echo "This is a new file." > new_file.txt

      - name: Add new file
        run: |
          git add new_file.txt

      - name: Commit changes
        run: |
          git commit -m "Add new file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
