# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
#  schedule:
#    - cron: '0 0/1 * * * ?'
  push:
    branches:
    - master
    paths-ignore:
      - README.md
      - .github/workflows/generate-active-chart.yml.yml
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg
      - name: Configure Git
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push to master
        run: |
         git push --force https://github.com/Ellioben/Ellioben.git master
         with:
         github_token: ${{ env.GITHUB_TOKEN }}
         branch: master
         force: true
         tags: latest

      
