# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
#  schedule:
#    - cron: '0 0/1 * * * ?'
  push:
    branches:
    - master
    paths-ignore:
      - README.md
      - .github/workflows/generate-active-chart.yml.yml
env:
  GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.5.0        
        with:
         target_branch: master
         build_dir: ./assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
