# This is a basic workflow to help you get started with Actions

name: Outpush

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "0 0 * * *"
  # push:
    # branches: 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README.md
        run: node index.js > README.md

      - name: Append README.md
        run: cat README.md >> README.md

      - name: Generate report
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg

      - name: Commit files
        run: |
          git config --global user.email "xieyongbo@tom.com"
          git config --global user.name "ellioben"
          git add .
          git commit -a -m "Update changes"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: ${{ github.ref }}
